environment: dev

replicas: 1

image:
  repository: aymensegni
  name: bookish-meme_server
  tag: v0.0.1


secrets:
  postgresql:
    userKey: postgresqlUsername
    databaseKey: postgresqlDatabase
    passwordKey: postgresqlPassword


resources:
  requests:
    cpu: 200m
    memory: 100Mi
  limit:
    cpu: 500m
    memory: 512Mi
