apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  user: {{ .Values.secrets.postgresql.user }}
  password: {{ .Values.secrets.postgresql.password }}
  database: {{ .Values.secrets.postgresql.database }}
